const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="tempmail1ff@gmail.com"
global.location="Bharat"


global.mongodb= process.env.MONGODB_URI || "mongodb://atlas-sql-66969a2aca2a7a310db3b7b7-uwotb.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "postgresql://bot_h6qn_user:eSlGCLXyzRPaqkhSgSwt2SAdhDkgkKVC@dpg-cqh24uss1f4s73bhum30-a.singapore-postgres.render.com/bot_h6qn"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Kolkata";
global.github=process.env.GITHUB|| "https://github.com/Jatingehlot05/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va5J2l489inmnfP8jQ1Z";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va5J2l489inmnfP8jQ1Z" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ IAMJ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "919650985680";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,919xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,919xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "919650985680,919xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_09_46_07_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICAxOTcsXG4gICAgICAgIDE2NixcbiAgICAgICAgODQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTA0LFxuICAgICAgICA2OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMjIsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTk5LFxuICAgICAgICA1MCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTUsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNjMsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTU0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjEsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMjksXG4gICAgICAgIDIyMCxcbiAgICAgICAgNjcsXG4gICAgICAgIDc0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQwLFxuICAgICAgICAyLFxuICAgICAgICA0LFxuICAgICAgICAxNTcsXG4gICAgICAgIDM1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjYsXG4gICAgICAgIDY0LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE1LFxuICAgICAgICA4MCxcbiAgICAgICAgMTE3LFxuICAgICAgICAyMTYsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTM1LFxuICAgICAgICAxNCxcbiAgICAgICAgMzIsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNDQsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNDYsXG4gICAgICAgIDM2LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxOSxcbiAgICAgICAgMjE5LFxuICAgICAgICAzOCxcbiAgICAgICAgNjAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTA1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjgsXG4gICAgICAgIDM1LFxuICAgICAgICA5OSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjMzLFxuICAgICAgICAyMjIsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjgsXG4gICAgICAgIDIwNixcbiAgICAgICAgNTAsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDUsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNDAsXG4gICAgICAgIDgyLFxuICAgICAgICAyMzksXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTcsXG4gICAgICAgIDgsXG4gICAgICAgIDc1LFxuICAgICAgICAyNDQsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDc2LFxuICAgICAgICAxNTQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTA2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExNSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNzksXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTY4LFxuICAgICAgICAxMixcbiAgICAgICAgMTMyLFxuICAgICAgICAxMCxcbiAgICAgICAgMTcxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxLFxuICAgICAgICAxODQsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTI0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMzQsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNjgsXG4gICAgICAgIDExMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxODEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNyxcbiAgICAgICAgMjA1LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgOTcsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjE1LFxuICAgICAgICAxODgsXG4gICAgICAgIDEyMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDc1LFxuICAgICAgICAxODksXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNDEsXG4gICAgICAgIDIzLFxuICAgICAgICA5OSxcbiAgICAgICAgMTQyLFxuICAgICAgICA1NixcbiAgICAgICAgMTg2LFxuICAgICAgICA2NixcbiAgICAgICAgMTAxLFxuICAgICAgICA4NixcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkxLFxuICAgICAgICAxMjksXG4gICAgICAgIDY5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMTYsXG4gICAgICAgIDExNixcbiAgICAgICAgMTYwLFxuICAgICAgICAzMCxcbiAgICAgICAgOSxcbiAgICAgICAgNjYsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTQ0LFxuICAgICAgICA2MixcbiAgICAgICAgMjksXG4gICAgICAgIDE1NSxcbiAgICAgICAgNDEsXG4gICAgICAgIDIyMSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE5LFxuICAgICAgICAzMixcbiAgICAgICAgMTI2LFxuICAgICAgICAzNyxcbiAgICAgICAgMTQyLFxuICAgICAgICA3LFxuICAgICAgICA2OSxcbiAgICAgICAgMTcwLFxuICAgICAgICA0NyxcbiAgICAgICAgNjYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxNixcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICA5OFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDgyXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjQ0LFxuICAgICAgICA5NCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE5NixcbiAgICAgICAgMzksXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDc2LFxuICAgICAgICAxOTIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNzYsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjQsXG4gICAgICAgIDEyMixcbiAgICAgICAgNTcsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTA4LFxuICAgICAgICA3MixcbiAgICAgICAgMTUxLFxuICAgICAgICAyLFxuICAgICAgICAxMDUsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjExLFxuICAgICAgICAxNzEsXG4gICAgICAgIDY4LFxuICAgICAgICA5OSxcbiAgICAgICAgMjExLFxuICAgICAgICAxMCxcbiAgICAgICAgNTYsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTUwLFxuICAgICAgICA3MyxcbiAgICAgICAgMzAsXG4gICAgICAgIDM5LFxuICAgICAgICAxNSxcbiAgICAgICAgMTksXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjExLFxuICAgICAgICAxMDQsXG4gICAgICAgIDEyOSxcbiAgICAgICAgNDYsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNzUsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMzIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTcxLFxuICAgICAgICAxMTYsXG4gICAgICAgIDEzMixcbiAgICAgICAgNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjQxLFxuICBcImFkdlNlY3JldEtleVwiOiBcInlSODYzZWIrUWI4OW9Uc05KNmJ2UDhVMFVrNm1WR1pZeEVFOFZjRUtSZ2c9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTE5NjUwOTg1NjgwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJENDBBMDBBMzhEQzU3RjNCM0FGREI5NzhGNTFEOTMzRlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjE5MDA4MTFcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MTk2NTA5ODU2ODBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkI1QkY5NjAyRkQ4NjQwNTRGMTUwMzk0ODQ1NzFDNTJDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTkwMDgxMVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkxOTY1MDk4NTY4MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiODY0NjVCODlBQzJGN0ZBNDg0NDdEMkVGMDlGQjhBQzBcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIxOTAwODE2XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIklLR2hWdmx1UUhtOWpUVFdiTGJYM2dcIixcbiAgXCJwaG9uZUlkXCI6IFwiMGM4YjdiZTQtYTQ4Zi00MWRmLWIyZWMtYmFkM2JkNTMxYmRhXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDU5LFxuICAgICAgMTU0LFxuICAgICAgODYsXG4gICAgICAxMjgsXG4gICAgICAyMDAsXG4gICAgICA2MixcbiAgICAgIDI0MixcbiAgICAgIDUsXG4gICAgICAxMjEsXG4gICAgICAxMjYsXG4gICAgICAxMTgsXG4gICAgICAxNzYsXG4gICAgICAyMTQsXG4gICAgICAyMTgsXG4gICAgICAxNDksXG4gICAgICA3NixcbiAgICAgIDIzNSxcbiAgICAgIDE2NixcbiAgICAgIDY1LFxuICAgICAgNlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4OCxcbiAgICAgIDIwNyxcbiAgICAgIDIwOCxcbiAgICAgIDE5NixcbiAgICAgIDIxOSxcbiAgICAgIDE4MSxcbiAgICAgIDIsXG4gICAgICAxODQsXG4gICAgICA0NixcbiAgICAgIDU3LFxuICAgICAgMTYwLFxuICAgICAgMjExLFxuICAgICAgMjM2LFxuICAgICAgODksXG4gICAgICAxMCxcbiAgICAgIDE1MixcbiAgICAgIDIwLFxuICAgICAgNjIsXG4gICAgICAyMTgsXG4gICAgICAwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkdMV1IxU0RQXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MTk2NTA5ODU2ODA6OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTcwOTgzMTM0NTk3MTkwOjhAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiVmVkaWNvbmNlcHRzIEJvdFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0xYVW9wOENFSWEraUxVR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwicFpGa2V6TDF6YTJsbW5TYm0zZlhRR3BvQTZOdWhua0VEZGh2YXVOWURTbz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI1aW9QT3NrSXdVUWc4aEMyTGJFWjQ0ZTRObFlONVN6c1hhTWhMTCtWYkpoZE80QVlHdkhQWVd1MjBEcFVLdXJpWDFtNmtPdXNKOWJnYXZjdVhwUkxDQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJjbDlkeU9SWUtMMmxHUzBZemZSQ0gwOGZxaWxEQnJ4dEFrbW1xVXhRYmJzUzlLQVp1ODhXOENQanV0eDU2WDN6QWJjbkNiZUFjc05WakpnRkNyU2lCUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MTk2NTA5ODU2ODA6OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICA0MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MTk2NTA5ODU2ODA6OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICA0MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIxOTAwODA5LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSXkzXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJeTMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJKTndaUVVKdnhsaW9JQmcvNGhwZ3JRUlh2a0wyMHh5bmVxakdjNXc5ZGJzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjYwMjQ1MDQ4NixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzIxOTAwODExNDM5XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "IAMJ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "VC Bot",
  ownername:process.env.OWNER_NAME|| "IAMJ",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
